best_params:
  criterion: friedman_mse
  learning_rate: 0.1
  loss: squared_error
  max_depth: 3
  max_features: auto
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 100
  random_state: 42
  subsample: 0.8
feature_selection: vif
model: gradient_boosting
test_metrics:
  explained_variance: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    1MJc32Ow5j8=
  mae: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    SB40INY82D8=
  mse: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    MwGAtDRU0j8=
  r2: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    dENE5wuw5j8=
timestamp: '20250423_020949'
training_metrics:
  explained_variance: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    qUapX7zV5z8=
  mae: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    fzTBdZ9S1z8=
  mse: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    2Z2M5vRk0D8=
  r2: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    rM76fLrV5z8=
tuning_method: grid
