best_params:
  colsample_bytree: 0.8
  enable_categorical: false
  learning_rate: 0.1
  max_depth: 5
  min_child_weight: 1
  n_estimators: 100
  nthread: -1
  objective: reg:squarederror
  subsample: 0.8
  tree_method: hist
feature_selection: k_best
model: xgboost
test_metrics:
  explained_variance: !!python/object/apply:numpy.core.multiarray.scalar
  - &id002 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAwLnG6T8=
  mae: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    4XOYPg==
  mse: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    S/9DPg==
  r2: !!python/object/apply:numpy.core.multiarray.scalar
  - *id002
  - !!binary |
    OVtMqrnG6T8=
timestamp: '20250423_024619'
training_metrics:
  explained_variance: !!python/object/apply:numpy.core.multiarray.scalar
  - *id002
  - !!binary |
    AAAAgMYB6z8=
  mae: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    PcmNPg==
  mse: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0GcgPg==
  r2: !!python/object/apply:numpy.core.multiarray.scalar
  - *id002
  - !!binary |
    2wUROsYB6z8=
tuning_method: random
